### PR TITLE
Fix `saveVideo` method return null

### LINKED ISSUE #327: await PhotoManager.editor.saveVideo return `null`
无法使用。这个方法。返回结果为null.无法得到实体

### PR DESCRIPTION
**Pull request by fxfSean**
Fixes #327 . Create the saving directory if it's not exist.

### CODE REVIEW

**Comment by AlexV525** [comment]
Thanks for the fix! Did you checked whether other *DBUtils need the same fix?

**Comment by fxfSean** [comment]
> Thanks for the fix! Did you checked whether other *DBUtils need the same fix?

not yet , I just met this problem on this single machine ,and if other *DBUtils has the same way implement, I think it is needed

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt [hunk 1]
```diff
@@ -519,7 +519,12 @@ object DBUtils : IDBUtils {
             inputStream.close()
         } else {
             val tmpPath = assetEntity?.path!!
-            val tmpFile = File(tmpPath)
+            var tmpFile = File(tmpPath)
```
Comment (AlexV525) [inline android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:522]: This fix didn't apply to the `saveVideo` actually, it applied to the `saveImage`.

**Review by AlexV525 — CHANGES_REQUESTED** [review]

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt (hunk 1 above)
Comment (fxfSean) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:522]: sorry😓 ,I just pasted the code to the wrong place

Comment (fxfSean) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:522]: I just test the `saveImageWithPath` method ,it has the same problem , before apply the code it returns null
image
after apply the code it works ok
image

Comment (AlexV525) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:522]: So it should be applied to every save methods. Thanks for these further tests.

**Comment by AlexV525** [comment]
After all methods been taken care, this PR will be ready for merge.

**Comment by AlexV525** [comment]
> 是否有验证过通过 bytes 保存图片的方法是否存在这个问题？

Did you verify whether the image bytes saving method will occur this problem?

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt [hunk 2]
```diff
@@ -519,7 +519,12 @@ object DBUtils : IDBUtils {
...
+            val directoryFile = File(tmpFile.parent!!)
```
Comment (AlexV525) [inline android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:523]: Can we use `tmpFile.parentFile!!` instead of `File(tmpFile.parent!!)`?

**Comment by AlexV525** [comment]
We should add the directory creation to both `Android30DbUtils` and `AndroidQDBUtils`.

image

**Comment by fxfSean** [comment]
> > 是否有验证过通过 bytes 保存图片的方法是否存在这个问题？
> 
> Did you verify whether the image bytes saving method will occur this problem?

> 通过 bytes 保存图片有同样的问题，我新提交了代码，增加判断

this method `saveImageWithBytes` has the same problem , i pushed the supplement code ,adding judgement logic moment ago

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/CommonExt.kt [hunk 3]
```diff
@@ -21,3 +22,13 @@ fun useFilePath(): Boolean {
...
+
+/**
+ * Check if the directories exists, if not, create it
+ */
+fun String.checkDirs() {
+    val targetFile = File(this)
+    if (!targetFile.parentFile!!.exists()){
+        targetFile.parentFile!!.mkdirs()
+    }
+}
```
Comment (AlexV525) [inline android/src/main/kotlin/top/kikt/imagescanner/core/utils/CommonExt.kt:34]: Need an empty line for EOF.

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt [hunk 4]
```diff
@@ -436,6 +436,7 @@ object DBUtils : IDBUtils {
         cursor.use {
             if (cursor.moveToNext()) {
                 val targetPath = cursor.getString(0)
+                targetPath.checkDirs()
```
Comment (AlexV525) [inline android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:439]: Can you apply the fix to other DBUtils too?

Comment (fxfSean) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:439]: sure, give me a minute

Comment (fxfSean) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:439]: I tested two Android 10 devices, Huawei mateX and Google Pixel3 , and it works ok with the `saveVideo` method, meanwhile the other DBUtils has the different implement, so I think it is no need to apply the fix to them

Comment (AlexV525) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:439]: I think it's necessary because most of feedbacks are using devices with Android 10 and 11, which also require a path check before the insertion.

Comment (fxfSean) [reply android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt:439]: done.

File: android/src/main/kotlin/top/kikt/imagescanner/core/utils/CommonExt.kt [hunk 5]
```diff
@@ -21,3 +22,13 @@ fun useFilePath(): Boolean {
         else -> true
     }
 }
+
+/**
+ * Check if the directories exists, if not, create it
```
Comment (AlexV525) [inline android/src/main/kotlin/top/kikt/imagescanner/core/utils/CommonExt.kt:27]:
```suggestion
 * Create the directory if it's not exist.
```

File: example/lib/page/save_image_example.dart [hunk 6]
```diff
@@ -38,11 +38,12 @@ class _SaveMediaExampleState extends State<SaveMediaExample> {
     if (Platform.isIOS || Platform.isMacOS) {
       dir = (await getApplicationSupportDirectory()).absolute.path;
     } else if (Platform.isAndroid) {
-      dir = (await getExternalStorageDirectories(
-        type: StorageDirectory.downloads,
-      ))![0]
-          .absolute
-          .path;
+      // dir = (await getExternalStorageDirectories(
```
Comment (AlexV525) [inline example/lib/page/save_image_example.dart:41]: Remove this?

**Review by AlexV525 — COMMENTED** [review]
Almost done, just some nit pickings.

File: example/lib/page/save_image_example.dart (hunk 6 above)
Comment (fxfSean) [reply example/lib/page/save_image_example.dart:41]: these two `dir` path represent two different way in `DBUtils`->`saveImage` 
```
if (savePath) { //true or false
    inputStream.close()
} else {
 ...
```
so, I suggest keep this

Comment (AlexV525) [reply example/lib/page/save_image_example.dart:41]: No, I mean the commented out part.

Comment (fxfSean) [reply example/lib/page/save_image_example.dart:41]: I changed it back, since the `saveVideo` method has acquired `getTemporaryDirectory` path, so it can cover this two cases

**Review by AlexV525 — APPROVED** [review]
RSLGTM. Now I think we're covered most of saving failed cases. Thanks for this solid fix! 👍
